#!/bin/sh
### BEGIN INIT INFO
# Provides:          firealarm
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: firealarm initscript
# Description:       firealarm
### END INIT INFO

case "$1" in
	start)
		/usr/bin/ruby /home/tallakt/prosjekter/firealarm/firealarm.rb start
	;;
	stop)
		/usr/bin/ruby /home/tallakt/prosjekter/firealarm/firealarm.rb stop
	;;
	restart)
		/usr/bin/ruby /home/tallakt/prosjekter/firealarm/firealarm.rb restart
	;;
	*)
		echo "Usage: $SCRIPT_NAME {start|stop|restart}" >&2
		exit 3
	;;
esac





